# Site Metadata
title: "#RevisitingSSI"
subtitle: "Revisiting Self-Sovereign Identity"
description: "Workshops focused on addressing harms and opportunities overlooked by mainstream Self-Sovereign Identity"
name: "Christopher Allen"
email: "ChristopherA@LifeWithAlacrity.com"
url: "https://RevisitingSSI.com"
baseurl: ""
repository: "RevisitingSSI/RevisitingSSI.com"

# Remote Theme
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"
search: true
lunr:
  search_within_pages: true

# Required Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

# Collections
collections:
  pages:
    output: true

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Author
author:
  name: "Christopher Allen"
  avatar: "/assets/images/ChristopherA-avatar.png"
  bio: "Blockchain & Decentralized Identity Architect — Internet Cryptography Pioneer — Co-author TLS Security Standard — Collaborative Tools & Patterns"
  location: "SF East Bay, California, USA"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ChristopherA"
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://www.lifewithalacrity.com"

# Header

# Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/RevisitingSSI"

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      classes:
        - wide
      header:
          overlay_color: "#000"
          overlay_filter: "0.5"
          overlay_image: /assets/images/rssi-header.jpg
          show_overlay_excerpt: false
      sidebar:
        nav:
          - reading
          - othersites

# Build Settings
permalink: /:title/
timezone: America/Los_Angeles

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
